### ISSUE TITLE
ERROR: network Error : dial tcp 127.0.0.1:1883: connect: connection refused

### ISSUE THREAD

**Issue by keensy** [MickMake/HomeAssistantAddons#1]
Able to enter icloud login details but unable to retrieve any information and addon is not listed in sidebar

Error In logs start with
ERROR: network Error : dial tcp 127.0.0.1:1883: connect: connection refused

**Comment by MickMake** [comment]
I believe you should be able to point just the MQTT server IP address at your local IP address that you use for your HA instance, or use "ha.local".
