### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by zachkont** [MickMake/HomeAssistantAddons#13]
When I set it up it says account does not exist. This is most likely due to the fact that my account is on the eu server, not the au. However, I cannot figure out the correct gateway to use, could you please guide me?

I tried `https://eugateway.isolarcloud.com` but it looks like their certificate is expired and event testing with `http://eugateway.isolarcloud.com` does not work

```
[15:05:51] INFO: Login to iSolarCloud using gateway https://augateway.isolarcloud.com ...
Error: Account does not exist '账号不存在'
Usage:
  GoSungrow api login [flags]
Examples:
	GoSungrow api login  
Flags: Use "GoSungrow help flags" for more info.
Additional help topics:
ERROR: Account does not exist '账号不存在'
```

I also tried `portaleu.isolarcloud.com` but I get a 405 method not allowed

**Comment by HermesDE** [comment]
https://gateway.isolarcloud.eu worked for me

**Comment by zachkont** [comment]
> [gateway.isolarcloud.eu](https://gateway.isolarcloud.eu) worked for me

This worked for me as well, thanks!
