### ISSUE TITLE
Error: network Error : dial tcp: lookup core-mosquitto on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by TaxmanNo1** [MickMake/HomeAssistantAddons#16]
Hello,

i´m able to login iSolarCloud, but after 2 devices found at Sungrow the following error shows up:

Error: network Error : dial tcp: lookup core-mosquitto on 127.0.0.11:53: no such host
Usage:
  GoSungrow mqtt run [flags]
Aliases:
  run, 
Examples:
	GoSungrow mqtt run  
Flags: Use "GoSungrow help flags" for more info.
Additional help topics:
ERROR: network Error : dial tcp: lookup core-mosquitto on 127.0.0.11:53: no such host
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by TaxmanNo1** [comment]
.... installed the mqtt server ....

sorry...  for... stupid...  questions...    :-)

**Comment by copetogo** [comment]
> .... installed the mqtt server ....
> 
> sorry... for... stupid... questions... :-)

hey i put the IP address in the mqtt host but still not able to setup the mqtt. already have mqtt setup for other services including frigate using local ip .i am attaching my config page and error log . Not sure what i am doing wrong
![Screenshot 2023-05-22 at 11 30 21 AM](https://github.com/MickMake/HomeAssistantAddons/assets/96839787/c2d7aef3-f6b7-4cc5-9474-3b8d15dd5960)
![Screenshot 2023-05-22 at 11 34 31 AM](https://github.com/MickMake/HomeAssistantAddons/assets/96839787/8df1236a-d0b0-47f7-8bc0-b02de5f1772f)
