### ISSUE TITLE
Error when installing 

### ISSUE THREAD

**Issue by arttwentyfourseven** [MickMake/HomeAssistantAddons#2]
Hi MickMake, I’m trying to install GoSungrow 2.2.0 for the first time. When hitting the Install button I’m getting the following error: “The command '/bin/ash -o pipefail -c chmod a+x /usr/local/bin/run.sh /usr/local/bin/getUrl.sh && /usr/local/bin/getUrl.sh' returned a non-zero code: 1”. Hassio 2022.5.5 running on pi4. Note that I don’t have an inverter yet; just checking whether or not this works.

Any ideas please?

**Comment by MickMake** [comment]
Yeah. It seems that the way I'm detecting which binary to download is the issue here.
I'll have a look at it next week, (little busy this week).

**Comment by jpillora** [comment]
![image](https://user-images.githubusercontent.com/633843/190934885-b916d589-ac71-4aff-b6ac-cdb76c1b4611.png)

**Comment by jpillora** [comment]
🎉

**Comment by Ralphy140** [comment]
Hey Mick, Just tried to update (yep been waiting for V3 to drop :) ) and I am still getting this same error on 2 different systems, 1 is a Pi and 1 is a NUC.

**Comment by MickMake** [comment]
OK. So, after a bit of a false start. We now have v3.0.1 of the HA addon, which runs v3.0.0 of GoSungrow.

Bit of a mess with trying to auto-configure MQTT. So I left it out and it defaults to requiring username/password.

This release was a bit of a strain. @jpillora - I didn't quite finish making it a proper package.
I just need to add docs and tidy up a bit.

**Comment by jpillora** [comment]
No worries
Will test out the HA plugin soon 👌

**Comment by weathers-aw** [comment]
Hi Mick,
I just tried to install this add-on for the first time - v3.0.3 and received a similar error regarding the setup.sh script:

**Failed to install add-on**
     _The command '/bin/ash -o pipefail -c chmod a+x /usr/local/bin/setup.sh && /usr/local/bin/setup.sh' returned a non-zero code: 1_

New HAOS install on a RPi2.
Only other addon installed was HACS as I initally thought your addon was available there (before reading the instructions in full).

Any advice on fixing this issue would be greatly appreciated.

Thanks for all the effort to date.

**Comment by waterwayne** [comment]
> Hi Mick, I just tried to install this add-on for the first time - v3.0.3 and received a similar error regarding the setup.sh script:
> 
> **Failed to install add-on** _The command '/bin/ash -o pipefail -c chmod a+x /usr/local/bin/setup.sh && /usr/local/bin/setup.sh' returned a non-zero code: 1_
> 
> New HAOS install on a RPi2. Only other addon installed was HACS as I initally thought your addon was available there (before reading the instructions in full).
> 
> Any advice on fixing this issue would be greatly appreciated.
> 
> Thanks for all the effort to date.

I am getting the same error as well.

**Failed to install add-on**
The command '/bin/ash -o pipefail -c chmod a+x /usr/local/bin/setup.sh && /usr/local/bin/setup.sh' returned a non-zero code: 1

Have tried removing the repository and reinstalling but am still getting the same error message. Mine is HAOS installed on a **RPi3.** Is this a hardware version-related issue?? Really like to get this add-on to work and much appreciate for any help.
