### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by bdog720** [MickMake/HomeAssistantAddons#3]
Seems to be related to the latest version of HA: [HA Breaking Changes](https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/)

**Comment by LeehamElectronics** [comment]
I don't understand, how do you fix this? how do you `"Add init: false to your addon's config.yaml"` ?
Thanks

**Comment by bjeanes** [comment]
Yup I also get this.

@LeehamElectronics I think @MickMake has to do that to https://github.com/MickMake/HomeAssistantAddons/blob/main/GoSungrow/config.yaml

**Comment by MickMake** [comment]
Fixed in the latest sub-release, (not v3 of GoSungrow).

**Comment by djp3k05** [comment]
> I don't understand, how do you fix this? how do you `"Add init: false to your addon's config.yaml"` ? Thanks

It was working fine on my side with v3.0.0.
Upgraded to v3.0.1 - working fine.
