### ISSUE TITLE
parse error after setting the config

### ISSUE THREAD

**Issue by sebutd** [MickMake/HomeAssistantAddons#5]
`[17:07:06] INFO: Setting up GoSungrow config ...
parse error: Expected string key before ':' at line 1, column 4`

After installing the AddOn "SunGrow" i changed the obligatory parameters. After a reboot i get the error above.
![image](https://user-images.githubusercontent.com/81180523/200895962-92a473ab-df84-4c3b-bda9-86e9e52f717e.png)

**Comment by hdymling** [comment]
Im geting smilar problem.

Not sure if this with the $Home are related to that we have delegated rights on our four inverters?

------------------------------------------------------------------
[11:47:59] INFO: Setting up GoSungrow config ...
parse error: Expected string key before ':' at line 1, column 4
[11:48:07] ERROR: Unknown HTTP error occured
[11:48:14] INFO: Writing GoSungrow config ...
ERROR: $HOME is not defined
[11:48:15] INFO: Login to iSolarCloud using gateway null ...
ERROR: $HOME is not defined
[11:48:15] INFO: Syncing data from gateway null ...
ERROR: $HOME is not defined
s6-rc: info: service legacy-services: stopping
--------------------------------

**Comment by Javbomb** [comment]
Yep I get this error too, some help would be greatly appreciated!

**Comment by MickMake** [comment]
Once I complete testing of v3, I'll update this addon.
Should be in the next week.

**Comment by amykapernick** [comment]
I'm having the same issues. Been fighting with getting Sungrow integrated so looking forward to seeing if this works

**Comment by MickMake** [comment]
Just letting you guys know that I have a new version dropping within the next week, (v3.0.0), which solves a lot of issues. Stay tuned.

**Comment by djp3k05** [comment]
we are waiting eagerly for the update 👯

**Comment by MickMake** [comment]
OK. v3.0.1 is now up! This fixes a LOT of issues. (Hopefully hasn't introduced more.)

Make sure to check out the lovelace examples, as the data returned may be a bit of an "eye glaze".

Have fun.
