### ISSUE TITLE
s6-rc: info: service errors in logs

### ISSUE THREAD

**Issue by rrutch** [MickMake/HomeAssistantAddons#6]
Log in HAS v2022.11.2 shows 

s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by MickMake** [comment]
Just letting you know that I have a new version dropping within the next week, (v3.0.0), which solves a lot of issues. Stay tuned.

**Comment by MickMake** [comment]
v3.0.1 is now up!
