### ISSUE TITLE
Images missing to get the lovelace yaml files working

### ISSUE THREAD

**Issue by arfoll** [MickMake/HomeAssistantAddons#7]
The lovelace basic I got configured relatively easily (shame your example uses _2 indexed units, mine are all _1, without that it would have worked just by changing the ps_id)

I couldn't find the images you have stored in /local though. So everything works once I installed the two front end addons canvas-gauge-card and mini-graph-card but the first status page doesn't give me the nice triangle view.

**Comment by MickMake** [comment]
OK. Added them in. Also changed the YAML files; _2 is now _1.

**Comment by arfoll** [comment]
Thanks alot for the ultra quick response! Closing the issue as all fixed. I'll try fixup the docu if I see any other small issues.
